# Generated by Django 4.1 on 2022-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_type', models.CharField(choices=[('WATER', 'water'), ('FOOD', 'food')], max_length=10)),
                ('packet_content', models.CharField(max_length=10)),
                ('calories', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('water_quantity_litres', models.PositiveIntegerField()),
            ],
        ),
    ]
