# Generated by Django 4.1 on 2022-08-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='packet_content',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='packet_type',
            field=models.CharField(blank=True, choices=[('WATER', 'water'), ('FOOD', 'food')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='water_quantity_litres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
