# Generated by Django 4.1 on 2022-08-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_alter_inventory_calories_alter_inventory_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='packet_content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
